### ISSUE TITLE
As a researcher, I want to be able to log in to SD Connect so that I can use the service I have applied access in MyCSC

### ISSUE THREAD

**Issue by juhtornr** [CSCfi/swift-browser-ui#546]
#### Describe the user story

In order to use SD Connect, it will be necessary to apply access in MyCSC. The information about the user right to use the service is used to determine if user can access the service or not.  

We could re-implement the login phase so that user would need to log in in two different phases. This would enable us to consume service profile information from (SDS) AAI.  

#### Tasks:
- [x] https://github.com/CSCfi/swift-browser-ui/pull/552
- [x] https://github.com/CSCfi/swift-browser-ui/issues/571
- [x] https://github.com/CSCfi/swift-browser-ui/issues/601
- [x] https://github.com/CSCfi/swift-browser-ui/issues/565
- [x] #605
- [x] #606

#### Testing 
This will be manually tested in test environment before approval. Unit tests implemented if relevant. 

#### Testing Definition of Done
Given that I log-in with valid user account and applied right to use the service when I do log-in to SD Connect then I expect to get into the service

**Comment by juhtornr** [comment]
fixes https://github.com/CSCfi/swift-browser-ui/issues/571

**Comment by csc-felipe** [comment]
This requires changes in MyCSC and SDS-AAI to be completed.
