### ISSUE TITLE
As a researcher, I need to download files in SD Connect that are encrypted with my own encryption key

### ISSUE THREAD

**Issue by juhtornr** [CSCfi/swift-browser-ui#576]
Edited by @sampsapenna adding description, DoD and tasks; description is expanded on in the comments.

Description copied over from #379

#### Description

> As a researcher I need to be able to download encrypted data that i can use in my research.
> 
> Data in SD-Connect is encrypted with services public key and we need to be able to add the researcher's public key for them to be able to download the data and use the data.
> 
> We might need a mechanism to obtain the researchers public key.
> Note: this service might need the private key to decrypt the header so it can add a new public key.
> 

> **If our public key has been added to recipients, we will support downloading as is:**, without the need for user's private key.

#### Tasks
* [ ] https://github.com/CSCfi/swift-browser-ui/issues/602
* [ ] https://github.com/CSCfi/swift-browser-ui/issues/604
* [ ] BONUS https://github.com/CSCfi/swift-browser-ui/issues/603

#### DoD (Definition of Done)

* The researcher has some way of adding their public key to the re-encryption service to enable downloads.
* The researcher can download the data re-encrypted with their own public key.
* BONUS: the researcher can add their private key temporarily for the UI to perform file decryption.

#### Testing

Peer review, Unit and Integration testing

**Comment by blankdots** [comment]
duplicate of: https://github.com/CSCfi/swift-browser-ui/issues/379

**Comment by blankdots** [comment]
also could this formulated as a `need`, because having phrased as a `want`, makes it a nice to have or it is up to debate if we should even consider implementing it.

**Comment by sampsapenna** [comment]
I'm closing https://github.com/CSCfi/swift-browser-ui/issues/379 after moving the description under this issue. Started splitting up different things into tasks to better keep track on things.
