### ISSUE TITLE
Add backend support for re-encryption service for adding headers

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#602]
#### Proposed solution

The header should be pushed to the header storage and re-encryption service instead of Allas. This will allow us to easily rotate the keys when required, and re-encrypt the header with the researcher's public key when they want to download the data back.

#### DoD (Definition of Done)

The upload service can push new headers into the header re-encryption service.

#### Tasks
* [x] add support for vault as default header storage
* [x] add backend functions for header store
* [x] add backend functions for header retrieve
* [x] add backend functions for whitelist entry
* [x] add backend functions for whitelist entry deletion
* [x] add backend functions for public key fetch

#### Testing

Unit tests, integration tests with a mock environment containing a Vault instance with our custom transit plugin.
There's a new issue for tests: #865
