### ISSUE TITLE
Share modal / Add View option to Permissions dropdown

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#855]
Design: https://www.figma.com/file/N0Y3N0nfyMS2wG3gjwZ201/SD-Connect-Prototype?node-id=1324%3A3749&t=vaqMZaxm97Vwk1kN-1

### Description
A new view option needs to be added, when sharing without instructing the c4ghtransit plugin to allow re-encrypting headers for another project. For the normal sharing, a separate issue will need to be created for adding a project whitelist additional to the ordinary whitelist, i.e. you can flag containers for access by other projects when needed. This is a separate task from viewing.

### Tasks
* [ ] add a view option to the sharing menu, that has the same functionality as the current "read, download, copy" option
* [ ] add support for whitelisting projects on folders in c4ghtransit
* [ ] add support for adding a project to the whitelist in c4ghtransit when sharing with the "read, download and copy" option

**Comment by juhtornr** [comment]
This is follow up to download features. @sampsapenna will formulate the task better. This is going to need some minor backend changes as well. @blankdots will give this a try.
